### ISSUE TITLE
Not working for IMG

### ISSUE THREAD

**Issue by bartoruiz** [marcelomazza/whatsapp-web-hide-media#14]
Has been like a week since Whatsapp change something and IMG does not hide

**Comment by marcelomazza** [comment]
Thanks for the report. I'm no longer supporting this extension, you can check for alternatives in the Chrome Store, for example: https://chrome.google.com/webstore/detail/privacy-extension-for-wha/jbojhlhhggfmmkpefknmbdhlaghehini
