### ISSUE TITLE
How does this extension work or what do I need to make it work?

### ISSUE THREAD

**Issue by AdrianKielbowicz** [marcelomazza/whatsapp-web-hide-media#2]
After installing the extension in my browser, WhatsApp Web looks exactly the same it did before. Do I need to do anything to activate it? The extension is definitely enabled in the browser.

**Comment by marcelomazza** [comment]
@AdrianKielbowicz nope, it should run automatically. It's super simple, just some custom css being loaded. Did you try reloading/reopening the WhatsApp Web tab?

**Comment by AdrianKielbowicz** [comment]
@marcelomazza All working now, relaunching the browser did the trick.

Thanks for a speedy reply though.
