### ISSUE TITLE
Stoped woking in the last 2 days

### ISSUE THREAD

**Issue by jonasrdm** [marcelomazza/whatsapp-web-hide-media#3]
An update to web.whatsapp must have broken the extension as it is not working anymore in the last few days. Awesome plugin, btw. I can help investigate

**Comment by marcelomazza** [comment]
Thanks! https://github.com/marcelomazza/whatsapp-web-hide-media/commit/33f0f6529ec7ff9a28cf898b5fd5661ab2eb850e should fix it, I should pushed the update to the Chrome Web Store 👍

**Comment by jonasrdm** [comment]
Cheers!
Almost everything seems to be fixed but unfortunately its not working for GIF's.

**Comment by marcelomazza** [comment]
Oops! Should be fixed with the next version 😄
