### ISSUE TITLE
Answer to link preview not hidden

### ISSUE THREAD

**Issue by therealmarv** [marcelomazza/whatsapp-web-hide-media#7]
Hi,
I don't know if this happened recently or it was always the case:
When answering to a link preview (e.g. sending a Youtube link) you can see the link preview in the answer.

Here is a screenshot to illustrate the bug:
![image](https://user-images.githubusercontent.com/1050582/37240127-e43e1b5a-244f-11e8-934b-83d55d01734d.png)

**Comment by therealmarv** [comment]
just a last remark: It would be bad to hide the whole answer because of understanding context, maybe it's possible to hide only the image (show on hover) in the preview?

**Comment by marcelomazza** [comment]
Hi, sorry I didn't see this issue before. This extension is no longer supported.
